version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    privileged: true
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itellectbase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d itellectbase -U postgres" ]
      interval: 20s
      timeout: 5s
      retries: 5

  redis:
    container_name: quotes_redis
    image: redis:latest
    expose:
      - 6379
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100


  backend:
    container_name: intellect_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    entrypoint: 
      sh -c "
        
        python manage.py migrate &&
        python manage.py add_base &&
        gunicorn config.wsgi --bind 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    restart: on-failure


volumes:
  postgres_data:
