# Generated by Django 4.2.7 on 2023-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbol', models.CharField(max_length=256, verbose_name='Simbol')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Edited')),
                ('time_quote', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
                ('open', models.FloatField(verbose_name='Open')),
                ('high', models.FloatField(verbose_name='High')),
                ('low', models.FloatField(verbose_name='Low')),
                ('close', models.FloatField(verbose_name='Close')),
                ('volume', models.IntegerField(verbose_name='Volume')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
